[CollectionView] Guard against a UIKit crash caused by attempting to scroll to an item that no longer exists (#142)
Calling `scrollToItem(…)` with in invalid index path raises an exception:

> NSInternalInconsistencyException: Attempted to scroll the collection view to an out-of-bounds item

We must guard against this to check to ensure that this never happens, as we call this method repeatedly and the items/section may change out from under us.